services:
  reverse-proxy:
    image: traefik:v2.11
    container_name: traefik-orchestrator
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik:/etc/traefik

networks:
  traefik-bridge:
    external: true