global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  format: common
  filePath: /etc/traefik/logs/traefik.log

accessLog:
  format: common
  filePath: /etc/traefik/logs/access.log
  bufferingSize: 128

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs: &trustedCloudflareIPs
      # https://www.cloudflare.com/ips/
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 172.64.0.0/13
      - 131.0.72.0/22
      - 2400:cb00::/32
      - 2606:4700::/32
      - 2803:f800::/32
      - 2405:b500::/32
      - 2405:8100::/32
      - 2a06:98c0::/29
      - 2c0f:f248::/32
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs: *trustedCloudflareIPs

  traefik:
    address: ":8080"
    http:
      middlewares:
        - "localnetwork@file"

  ping:
    address: ":8082"

api:
  dashboard: true
  insecure: true
  debug: true

ping:
  entryPoint: "ping"

serversTransport:
  insecureSkipVerify: true

http:
  middlewares:
    localnetwork:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.1.0/24"
        ipStrategy:
          depth: 0

certificatesResolvers:
  cloudflare:
    acme:
      email: '{{env "CF_API_EMAIL"}}'
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    exposedByDefault: false
    network: traefik-bridge
    watch: true
  file:
    directory: /etc/traefik
    filename: traefik.yml
    watch: true