global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  format: common
  filePath: /etc/traefik/logs/traefik.log

accessLog:
  format: common
  filePath: /etc/traefik/logs/access.log
  bufferingSize: 128

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"

  traefik:
    address: ":8080"
    http:
      middlewares:
        - "localnetwork@file"

api:
  dashboard: true
  insecure: true
  debug: true

serversTransport:
  insecureSkipVerify: true

http:
  middlewares:
    localnetwork:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.1.0/24"
        ipStrategy:
          depth: 0

certificatesResolvers:
  cloudflare:
    acme:
      email: "paul.marisoumary@gmail.com"
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    exposedByDefault: false
    network: traefik-bridge
    watch: true
  file:
    directory: /etc/traefik
    filename: traefik.yml
    watch: true